# Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager

# Info Kustomize doc:
# https://kubectl.docs.kubernetes.io/references/kustomize/
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autorightsizing-secret
  namespace: justice
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: autorightsizing-secret
    creationPolicy: "Owner"
  data:
    - secretKey: envBaseUrl
      remoteRef:
        key: /eks/${customer}/${project}/${environment}/justice_base_url
    - secretKey: clientId
      remoteRef:
        key: /eks/${customer}/${project}/${environment}/justice-iam-service/iam_client_id
    - secretKey: clientSecret
      remoteRef:
        key: /eks/${customer}/${project}/${environment}/justice-iam-service/iam_client_secret
    - secretKey: superUserEmail
      remoteRef:
        key: /eks/${customer}/${project}/${environment}/justice-iam-service/superuser
    - secretKey: superUserPassword
      remoteRef:
        key: /eks/${customer}/${project}/${environment}/justice-iam-service/superuser_password
    - secretKey: publisherNamespace
      remoteRef:
        key: /eks/${customer}/${project}/${environment}/justice_publisher_namespace
    - secretKey: publisherID
      remoteRef:
        key: /eks/${customer}/${project}/${environment}/justice-iam-service/iam_client_id
    - secretKey: publisherSecret
      remoteRef:
        key: /eks/${customer}/${project}/${environment}/justice-iam-service/iam_client_secret